apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: system
  labels:
    control-plane: sumologic-kubernetes-collection-helm-operator
spec:
  selector:
    matchLabels:
      control-plane: sumologic-kubernetes-collection-helm-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: sumologic-kubernetes-collection-helm-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=sumologic-kubernetes-collection-helm-operator
        image: controller
        name: operator
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: sumologic-kubernetes-collection-helm-operator
          - name: RELATED_IMAGE_KUBERNETES_SETUP
            value: public.ecr.aws/sumologic/kubernetes-setup:3.0.0-ubi
          - name: RELATED_IMAGE_NODE_EXPORTER
            value: public.ecr.aws/sumologic/node-exporter:v1.0.1-ubi
          - name: RELATED_IMAGE_KUBE_STATE_METRICS
            value: public.ecr.aws/sumologic/kube-state-metrics:v1.9.7-ubi
          - name: RELATED_IMAGE_PROMETHEUS_OPERATOR
            value: public.ecr.aws/sumologic/prometheus-operator:v0.43.2-ubi
          - name: RELATED_IMAGE_PROMETHEUS_CONFIG_RELOADER
            value: public.ecr.aws/sumologic/prometheus-config-reloader:v0.43.2-ubi
          - name: RELATED_IMAGE_PROMETHEUS
            value: public.ecr.aws/sumologic/prometheus:v2.22.1-ubi
          - name: RELATED_IMAGE_THANOS
            value: public.ecr.aws/sumologic/thanos:v0.10.0-ubi
          - name: RELATED_IMAGE_METRICS_SERVER
            value: public.ecr.aws/sumologic/metrics-server:0.4.2-debian-10-r58-ubi
          - name: RELATED_IMAGE_KUBE_RBAC_PROXY
            value: public.ecr.aws/sumologic/kube-rbac-proxy:v0.5.0-ubi
          - name: RELATED_IMAGE_TAILING_SIDECAR_OPERATOR
            value: ghcr.io/sumologic/tailing-sidecar-operator:0.3.1-ubi
          - name: RELATED_IMAGE_TAILING_SIDECAR
            value: ghcr.io/sumologic/tailing-sidecar:0.3.1-ubi
          - name: RELATED_IMAGE_TELEGRAF_OPERATOR
            value: public.ecr.aws/sumologic/telegraf-operator-ubi:v1.1.1
          - name: RELATED_IMAGE_TELEGRAF
            value: public.ecr.aws/sumologic/telegraf:1.14.4-ubi
          - name: RELATED_IMAGE_KUBERNETES_FLUENTD
            value: public.ecr.aws/sumologic/kubernetes-fluentd:1.12.2-sumo-0-ubi
          - name: RELATED_IMAGE_FLUENT_BIT
            value: public.ecr.aws/sumologic/fluent-bit:1.6.10-ubi
          - name: RELATED_IMAGE_FALCO
            value: public.ecr.aws/sumologic/falco:0.27.0
          - name: RELATED_IMAGE_SUMO_UBI_MINIMAL
            value: public.ecr.aws/sumologic/sumo-ubi-minimal:8.4
          - name: RELATED_IMAGE_OPENTELEMETRY_COLLECTOR
            value: public.ecr.aws/sumologic/opentelemetry-collector:0.22.0-sumo-ubi
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 100Mi
      serviceAccountName: helm-operator
      terminationGracePeriodSeconds: 10
